// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "DEVICE ID";

const char SSID[]               = "SSID";    // Network SSID (name)
const char PASS[]               = "WIFI PASSWORD";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "SECRET KEY";    // Secret device password

void onLedOnChange();

int uptime;
bool ledStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(uptime, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(ledStatus, READWRITE, ON_CHANGE, onLedOnChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
