/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/dbe67f67-1a08-4b10-9c70-457f4435df72 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int uptime;
  bool ledOn;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {

  pinMode(LED_BUILTIN, OUTPUT); //GPIO del led in modalità uscita digitale

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(4);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  uptime = millis() / 1000; //numero secondi da avvio CPU  
}


/*
  Since LedOn is READ_WRITE variable, onLedOnChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedOnChange()  {
  // Add your code here to act upon LedOn change
  Serial.write("ON LED CHANGE. LedOn Da cloud:");
  Serial.println(ledStatus);

  Serial.write("Valore aggiornato ledStatus:");
  Serial.println(ledStatus);  
  digitalWrite(LED_BUILTIN,!ledStatus);
}
